### ISSUE TITLE
Singularity 

### ISSUE THREAD

**Issue by JH36** [ODHL/SARS_CoV_2_Workflow#11]
Singularity has changed names to Apptainer (https://github.com/apptainer/singularity). 

Singularity's last version was 3.8.7 on March 2022.

Apptainer (https://github.com/apptainer/apptainer) was last updated last month and is version 1.1.6

**Comment by slsevilla** [comment]
Thanks for the update @JH36, but not sure how this is an issue related to ODHL's SARS pipeline?

**Comment by JH36** [comment]
It’s just in case someone uses singularity instead of docker in the config file as it’s an option. I stumbled across it today at work and thought I forked it on mine and realized it was ODHLs. Sent from my iPhoneOn Mar 16, 2023, at 11:26 AM, Samantha ***@***.***> wrote:﻿
Thanks for the update @JH36, but not sure how this is an issue related to ODHL's SARS pipeline?
